/**
 * Centralized demo / mock data for Phase 3 (Chat + Notifications).
 * Replace these with real API calls once the backend is ready.
 */

import type {Conversation, Message} from '@/types/message';
import type {AppNotification} from '@/types/notification';

// ─── Helpers ────────────────────────────────────────────────────────────────

function daysAgo(n: number): string {
    const d = new Date();
    d.setDate(d.getDate() - n);
    return d.toISOString();
}

function minsAgo(n: number): string {
    const d = new Date();
    d.setMinutes(d.getMinutes() - n);
    return d.toISOString();
}

/** Build a demo message with all required fields */
function msg(partial: Pick<Message, 'id' | 'conversation_id' | 'sender_id' | 'type' | 'body' | 'is_deleted' | 'delivered_at' | 'read_at' | 'created_at'> & {
    status?: Message['status']
}): Message {
    return {
        file_path: null,
        file_name: null,
        file_size: null,
        file_mime_type: null,
        duration_seconds: null,
        thumbnail_path: null,
        reactions: {},
        reply_to_message_id: null,
        reply_to: null,
        ...partial,
    };
}

// ─── Conversations ───────────────────────────────────────────────────────────

export const DEMO_CONVERSATIONS: Conversation[] = [
    {
        id: 1,
        participant: {
            id: 201,
            name: 'Sumaiya Rahman',
            avatar: null,
            is_online: true,
            last_seen_at: new Date().toISOString(),
            profile_id: 'MCT-001201',
            subscription_plan: 'gold',
        },
        last_message: {
            id: 1005,
            conversation_id: 1,
            sender_id: 201,
            type: 'text',
            body: 'Sure, I would love to know more about your family! 😊',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(5),
            read_at: null,
            created_at: minsAgo(5),
            status: 'delivered',
        },
        last_message_at: minsAgo(5),
        unread_count: 3,
        created_at: daysAgo(3),
    },
    {
        id: 2,
        participant: {
            id: 202,
            name: 'Nusrat Jahan',
            avatar: null,
            is_online: false,
            last_seen_at: minsAgo(45),
            profile_id: 'MCT-001202',
            subscription_plan: 'silver',
        },
        last_message: {
            id: 1010,
            conversation_id: 2,
            sender_id: 1, // current user
            type: 'text',
            body: 'Looking forward to hearing from you!',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(60),
            read_at: minsAgo(55),
            created_at: minsAgo(60),
            status: 'read',
        },
        last_message_at: minsAgo(60),
        unread_count: 0,
        created_at: daysAgo(5),
    },
    {
        id: 3,
        participant: {
            id: 203,
            name: 'Farhana Akter',
            avatar: null,
            is_online: true,
            last_seen_at: new Date().toISOString(),
            profile_id: 'MCT-001203',
            subscription_plan: 'platinum',
        },
        last_message: {
            id: 1020,
            conversation_id: 3,
            sender_id: 203,
            type: 'text',
            body: 'Alhamdulillah, everything is going well. How about you?',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(120),
            read_at: minsAgo(115),
            created_at: minsAgo(120),
            status: 'read',
        },
        last_message_at: minsAgo(120),
        unread_count: 0,
        created_at: daysAgo(7),
    },
    {
        id: 4,
        participant: {
            id: 204,
            name: 'Tania Islam',
            avatar: null,
            is_online: false,
            last_seen_at: daysAgo(1),
            profile_id: 'MCT-001204',
            subscription_plan: 'free',
        },
        last_message: {
            id: 1030,
            conversation_id: 4,
            sender_id: 204,
            type: 'text',
            body: 'Thank you for your interest 🌸',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(1),
            read_at: daysAgo(1),
            created_at: daysAgo(1),
            status: 'read',
        },
        last_message_at: daysAgo(1),
        unread_count: 1,
        created_at: daysAgo(10),
    },
    {
        id: 5,
        participant: {
            id: 205,
            name: 'Rifat Hossain',
            avatar: null,
            is_online: false,
            last_seen_at: daysAgo(2),
            profile_id: 'MCT-001205',
            subscription_plan: 'gold',
        },
        last_message: {
            id: 1040,
            conversation_id: 5,
            sender_id: 1,
            type: 'text',
            body: "That sounds great! Let's connect",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(2),
            read_at: null,
            created_at: daysAgo(2),
            status: 'delivered',
        },
        last_message_at: daysAgo(2),
        unread_count: 0,
        created_at: daysAgo(14),
    },
];

// ─── Messages per conversation ────────────────────────────────────────────────

export const DEMO_MESSAGES: Record<number, Message[]> = {
    1: [
        {
            id: 1001,
            conversation_id: 1,
            sender_id: 1,
            type: 'text',
            body: 'Assalamu Alaikum! I came across your profile and I think we could be a great match.',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(3),
            read_at: daysAgo(3),
            created_at: daysAgo(3),
            status: 'read',
        },
        {
            id: 1002,
            conversation_id: 1,
            sender_id: 201,
            type: 'text',
            body: 'Wa Alaikum Assalam! Thank you for reaching out. Your profile looks wonderful too! 😊',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(3),
            read_at: daysAgo(3),
            created_at: daysAgo(3),
            status: 'read',
        },
        {
            id: 1003,
            conversation_id: 1,
            sender_id: 1,
            type: 'text',
            body: "Thank you! I'm a software engineer from Dhaka. Could you tell me a bit about yourself and your family background?",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(2),
            read_at: daysAgo(2),
            created_at: daysAgo(2),
            status: 'read',
        },
        {
            id: 1004,
            conversation_id: 1,
            sender_id: 201,
            type: 'text',
            body: "I'm a teacher from Chittagong. I have a very supportive family. My father is a retired government officer and my mother is a housewife.",
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(30),
            read_at: minsAgo(28),
            created_at: minsAgo(30),
            status: 'read',
        },
        {
            id: 1005,
            conversation_id: 1,
            sender_id: 201,
            type: 'text',
            body: 'Sure, I would love to know more about your family! 😊',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(5),
            read_at: null,
            created_at: minsAgo(5),
            status: 'delivered',
        },
    ],
    2: [
        {
            id: 1006,
            conversation_id: 2,
            sender_id: 202,
            type: 'text',
            body: 'Hello! I noticed you shortlisted my profile. I appreciate that! 🌸',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(5),
            read_at: daysAgo(5),
            created_at: daysAgo(5),
            status: 'read',
        },
        {
            id: 1007,
            conversation_id: 2,
            sender_id: 1,
            type: 'text',
            body: "Yes, your profile is really impressive! I'd love to learn more about you.",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(4),
            read_at: daysAgo(4),
            created_at: daysAgo(4),
            status: 'read',
        },
        {
            id: 1008,
            conversation_id: 2,
            sender_id: 202,
            type: 'text',
            body: "Thank you! I'm currently working as a doctor in Dhaka Medical College. What do you do?",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(3),
            read_at: daysAgo(3),
            created_at: daysAgo(3),
            status: 'read',
        },
        {
            id: 1009,
            conversation_id: 2,
            sender_id: 1,
            type: 'text',
            body: "That's amazing! I'm a software engineer at a tech company.",
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(65),
            read_at: minsAgo(62),
            created_at: minsAgo(65),
            status: 'read',
        },
        {
            id: 1010,
            conversation_id: 2,
            sender_id: 1,
            type: 'text',
            body: 'Looking forward to hearing from you!',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(60),
            read_at: minsAgo(55),
            created_at: minsAgo(60),
            status: 'read',
        },
    ],
    3: [
        {
            id: 1011,
            conversation_id: 3,
            sender_id: 1,
            type: 'text',
            body: 'Salam! Hope you are doing well.',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(7),
            read_at: daysAgo(7),
            created_at: daysAgo(7),
            status: 'read',
        },
        {
            id: 1012,
            conversation_id: 3,
            sender_id: 203,
            type: 'text',
            body: 'Wa Salam! I am doing well, Alhamdulillah. How about you?',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(6),
            read_at: daysAgo(6),
            created_at: daysAgo(6),
            status: 'read',
        },
        {
            id: 1013,
            conversation_id: 3,
            sender_id: 1,
            type: 'text',
            body: "Alhamdulillah, I'm well too. Your profile mentions you are from Sylhet?",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(5),
            read_at: daysAgo(5),
            created_at: daysAgo(5),
            status: 'read',
        },
        {
            id: 1020,
            conversation_id: 3,
            sender_id: 203,
            type: 'text',
            body: 'Alhamdulillah, everything is going well. How about you?',
            file_path: null,
            is_deleted: false,
            delivered_at: minsAgo(120),
            read_at: minsAgo(115),
            created_at: minsAgo(120),
            status: 'read',
        },
    ],
    4: [
        {
            id: 1025,
            conversation_id: 4,
            sender_id: 204,
            type: 'text',
            body: 'Thank you for your interest 🌸',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(1),
            read_at: daysAgo(1),
            created_at: daysAgo(1),
            status: 'read',
        },
    ],
    5: [
        {
            id: 1035,
            conversation_id: 5,
            sender_id: 205,
            type: 'text',
            body: 'Hi! I saw your profile and would love to connect.',
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(3),
            read_at: daysAgo(3),
            created_at: daysAgo(3),
            status: 'read',
        },
        {
            id: 1040,
            conversation_id: 5,
            sender_id: 1,
            type: 'text',
            body: "That sounds great! Let's connect",
            file_path: null,
            is_deleted: false,
            delivered_at: daysAgo(2),
            read_at: null,
            created_at: daysAgo(2),
            status: 'delivered',
        },
    ],
};

// ─── Notifications ────────────────────────────────────────────────────────────

export const DEMO_NOTIFICATIONS: AppNotification[] = [
    {
        id: 'n001',
        type: 'interest_received',
        title: 'New Interest Received 💌',
        body: 'Sumaiya Rahman has sent you an interest request.',
        action_url: '/interests',
        avatar: null,
        is_read: false,
        read_at: null,
        created_at: minsAgo(10),
    },
    {
        id: 'n002',
        type: 'new_message',
        title: 'New Message 💬',
        body: 'Sumaiya Rahman: "Sure, I would love to know more about your family!"',
        action_url: '/chat/1',
        avatar: null,
        is_read: false,
        read_at: null,
        created_at: minsAgo(5),
    },
    {
        id: 'n003',
        type: 'interest_accepted',
        title: 'Interest Accepted 🎉',
        body: 'Nusrat Jahan has accepted your interest request! You can now chat.',
        action_url: '/chat/2',
        avatar: null,
        is_read: false,
        read_at: null,
        created_at: minsAgo(30),
    },
    {
        id: 'n004',
        type: 'profile_viewed',
        title: 'Profile Viewed 👀',
        body: 'Farhana Akter viewed your profile.',
        action_url: '/profile/203',
        avatar: null,
        is_read: true,
        read_at: minsAgo(60),
        created_at: minsAgo(60),
    },
    {
        id: 'n005',
        type: 'match_suggestion',
        title: "Today's Matches Ready 💑",
        body: 'We found 8 new compatible profiles for you today. Check them out!',
        action_url: '/matches',
        avatar: null,
        is_read: true,
        read_at: daysAgo(1),
        created_at: daysAgo(1),
    },
    {
        id: 'n006',
        type: 'interest_received',
        title: 'New Interest Received 💌',
        body: 'Tania Islam has sent you an interest request.',
        action_url: '/interests',
        avatar: null,
        is_read: true,
        read_at: daysAgo(1),
        created_at: daysAgo(1),
    },
    {
        id: 'n007',
        type: 'photo_approved',
        title: 'Photo Approved ✅',
        body: 'Your profile photo has been approved and is now visible to other members.',
        action_url: '/profile/edit',
        avatar: null,
        is_read: true,
        read_at: daysAgo(2),
        created_at: daysAgo(2),
    },
    {
        id: 'n008',
        type: 'system',
        title: 'Welcome! 🎊',
        body: 'Complete your profile to increase your chances of finding the perfect match.',
        action_url: '/profile/edit',
        avatar: null,
        is_read: true,
        read_at: daysAgo(3),
        created_at: daysAgo(3),
    },
    {
        id: 'n009',
        type: 'subscription_expiring',
        title: 'Subscription Expiring Soon ⚠️',
        body: 'Your Gold plan expires in 3 days. Renew now to keep your benefits.',
        action_url: '/subscription',
        avatar: null,
        is_read: false,
        read_at: null,
        created_at: minsAgo(180),
    },
];

